export const entireTransaction = {
    '2022-1': {
        9: [
            {
                category: '카페/간식',
                color: 'mint',
                content: '딸기 스무디',
                method: '토스',
                sign: '-',
                cost: '5900',
            },
        ],
        17: [
            {
                category: '카페/간식',
                color: 'mint',
                content: '아이스 아메리카노',
                method: '토스',
                sign: '-',
                cost: '3700',
            },
            {
                category: '식비',
                color: 'mint',
                content: '돈까스 & 제육볶음',
                method: '카카오페이',
                sign: '-',
                cost: '19000',
            },
        ],
        28: [
            {
                category: '카페/간식',
                color: 'mint',
                content: '녹차 스무디',
                method: '현금',
                sign: '-',
                cost: '5700',
            },
            {
                category: '카페/간식',
                color: 'mint',
                content: '딸기 스무디',
                method: '토스',
                sign: '-',
                cost: '5900',
            },
            {
                category: '식비',
                color: 'mint',
                content: '돈까스 & 제육볶음',
                method: '카카오페이',
                sign: '-',
                cost: '19000',
            },
            {
                category: '카페/간식',
                color: 'mint',
                content: '허니브레드',
                method: '현금',
                sign: '-',
                cost: '5300',
            },
            {
                category: '카페/간식',
                color: 'mint',
                content: '민트초코라떼',
                method: '현금',
                sign: '-',
                cost: '5200',
            },
            {
                category: '교통',
                color: 'mint',
                content: '카카오택시',
                method: '카카오페이',
                sign: '-',
                cost: '4700',
            },
            {
                category: '교통',
                color: 'mint',
                content: '버스',
                method: '카카오페이',
                sign: '-',
                cost: '1300',
            },
            {
                category: '카페/간식',
                color: 'mint',
                content: '쿠키앤크림',
                method: '카카오페이',
                sign: '-',
                cost: '6200',
            },
            {
                category: '카페/간식',
                color: 'mint',
                content: '치즈케이크',
                method: '현금',
                sign: '-',
                cost: '7300',
            },
            {
                category: '여행/숙박',
                color: 'mint',
                content: '신라호텔',
                method: '토스',
                sign: '-',
                cost: '170000',
            },
        ],
    },
    '2022-2': {
        9: [
            {
                category: '월급',
                color: 'mint',
                content: '월급 들어왔다아@!',
                method: '카카오페이',
                sign: '+',
                cost: '3880000',
            },
        ],
        17: [
            {
                category: '카페/간식',
                color: 'mint',
                content: '아이스 아메리카노',
                method: '토스',
                sign: '-',
                cost: '3700',
            },
            {
                category: '식비',
                color: 'mint',
                content: '돈까스 & 제육볶음',
                method: '카카오페이',
                sign: '-',
                cost: '19000',
            },
        ],
    },
};
