name: integration and deploy

on:
  push:
    branches:
      - main

jobs:
  set-node-version:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

  pull-repository:
    runs-on: ubuntu-18.04
    needs: set-node-version
    steps:
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/deploy/account-book
            git pull origin main
  yarn-backend:
    runs-on: ubuntu-18.04
    needs: pull-repository
    steps:
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/deploy/account-book/backend
            yarn
  yarn-frontend:
    runs-on: ubuntu-18.04
    needs: pull-repository
    steps:
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/deploy/account-book/frontend
            yarn
  build-frontend:
    runs-on: ubuntu-18.04
    needs: yarn-frontend
    steps:
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/deploy/account-book/frontend
            sudo rm -rf /var/www/account-book
            sudo mkdir /var/www/account-book
            sudo rm -rf dist
            yarn run build
            sudo cp -r dist/* /var/www/account-book
  restart-nginx:
    runs-on: ubuntu-18.04
    needs: build-frontend
    steps:
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo systemctl restart nginx
  restart-pm2:
    runs-on: ubuntu-18.04
    needs: [yarn-backend, restart-nginx]
    steps:
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            pm2 reload all
