name: OPEN PR 테스트

on:
  pull_request:
    branches: [deploy-test]

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: install dependency
        run: |
          cd frontend
          yarn

      - name: test
        run: |
          cd frontend
          yarn run test

      - name: pr-comment if test failed
        uses: actions/github-script@3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body: "실패한 테스트코드가 존재합니다.",
              event: "REQUEST_CHANGES"
            })
        if: failure()
